<?php

declare(strict_types=1);

use Contao\DataContainer;
use Contao\DC_Table;

/**
 * Curated FAQ entries per page. Generated by AI (unpublished), curated and
 * published by editors, rendered by the "seo_studio_faq" frontend module
 * with FAQPage JSON-LD.
 */
$GLOBALS['TL_DCA']['tl_seo_studio_faq'] = [
    'config' => [
        'dataContainer' => DC_Table::class,
        'enableVersioning' => true,
        'sql' => [
            'keys' => [
                'id' => 'primary',
                'pid,published' => 'index',
            ],
        ],
    ],
    'list' => [
        'sorting' => [
            'mode' => DataContainer::MODE_SORTABLE,
            'fields' => ['pid', 'sorting'],
            'panelLayout' => 'filter;search,limit',
        ],
        'label' => [
            'fields' => ['question'],
            'format' => '%s',
            'label_callback' => static function (array $row, string $label): string {
                $page = \Contao\PageModel::findByPk($row['pid']);
                $pageTitle = $page !== null ? $page->title : '?';

                return sprintf('%s <span style="color:#999;padding-left:6px">[%s]</span>', $label, $pageTitle);
            },
        ],
        'operations' => [
            'edit' => ['href' => 'act=edit', 'icon' => 'edit.svg'],
            'delete' => [
                'href' => 'act=delete',
                'icon' => 'delete.svg',
                'attributes' => 'onclick="if(!confirm(\'Eintrag wirklich löschen?\'))return false;Backend.getScrollOffset()"',
            ],
            'toggle' => ['href' => 'act=toggle&amp;field=published', 'icon' => 'visible.svg'],
            'show' => ['href' => 'act=show', 'icon' => 'show.svg'],
        ],
    ],
    'palettes' => [
        'default' => '{faq_legend},pid,question,answer;{publish_legend},published',
    ],
    'fields' => [
        'id' => [
            'sql' => 'int(10) unsigned NOT NULL auto_increment',
        ],
        'tstamp' => [
            'sql' => "int(10) unsigned NOT NULL default 0",
        ],
        'sorting' => [
            'sql' => "int(10) unsigned NOT NULL default 0",
        ],
        'pid' => [
            'inputType' => 'pageTree',
            'foreignKey' => 'tl_page.title',
            'eval' => ['mandatory' => true, 'fieldType' => 'radio', 'tl_class' => 'clr'],
            'sql' => "int(10) unsigned NOT NULL default 0",
            'relation' => ['type' => 'hasOne', 'load' => 'lazy'],
        ],
        'question' => [
            'inputType' => 'text',
            'exclude' => true,
            'search' => true,
            'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'long'],
            'sql' => "varchar(255) NOT NULL default ''",
        ],
        'answer' => [
            'inputType' => 'textarea',
            'exclude' => true,
            'search' => true,
            'eval' => ['mandatory' => true, 'rte' => 'tinyMCE', 'tl_class' => 'clr'],
            'sql' => 'text NULL',
        ],
        'published' => [
            'inputType' => 'checkbox',
            'exclude' => true,
            'filter' => true,
            'toggle' => true,
            'eval' => ['doNotCopy' => true],
            'sql' => "char(1) NOT NULL default ''",
        ],
    ],
];
